### ISSUE TITLE
Allow backend to be removed by name

### ISSUE THREAD

**Issue by ahelm** [GoLP-IST/nata#108]
Currently, all datasets following the `nata.types.DatasetType` protocol have a `.remove_backend` method. However, to remove a backend, one has to provide the corresponding backend as an object. It would be better if we could remove backends based on the name as well.

## TODO

- [ ] Change protocol `nata.types.DatasetType`
- [ ] Change implementation for `nata.containers.GridDataset`
- [ ] Change implementation for `nata.containers.ParticleDataset`

**Comment by ahelm** [comment]
Obsolete issue
